[WIP]Still building the framework.

diff --git a/bioxp b/bioxp
--- a/bioxp
+++ b/bioxp
@@ -1,1 +1,44 @@
 #!/usr/bin/env bash
+
+set -ue
+# FROM LIBISOPT V1P3
+function isopt() {
+    case "${1:-}" in
+    -? | --* | -?\:* | --*\:*)
+        return 0
+        ;;
+    *)
+        return 1
+        ;;
+    esac
+}
+DN="$(readlink -f "$(dirname "${0}")")"
+# ============ Possess arguments ============
+
+STDS=()
+for opt in "${@}"; do
+    if isopt "${opt}"; then
+        case "${opt}" in
+        "-h" | "--help")
+            echo "Help should be added here."
+            exit 0
+            ;;
+        "-v" | "--version")
+            echo "Version 0"
+            exit 0
+            ;;
+        esac
+    else
+        STDS=("${STDS[@]}" "${opt}")
+    fi
+done
+cmd=${STDS[0]:-}
+unset STDS[0]
+if [ -z "${cmd}" ]; then
+    exit 0
+elif [ -e "${DN}"/exec/bioxp_"${cmd}".sh ];then
+    bash "${DN}"/exec/bioxp_"${cmd}".sh "${STDS[@]}"
+else
+    echo -e "\e[31mERROR: Subcommand '${cmd}' invalid!\e[0m"
+    exit 1
+fi
